# Generated by Django 2.0.13 on 2019-11-08 02:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patter',
            fields=[
                ('patter_str', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('meaning_str', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
