# Generated by Django 2.0.13 on 2019-11-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patter', '0002_patter_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patter',
            name='meaning_str',
        ),
        migrations.AddField(
            model_name='patter',
            name='meaning_long_str',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='patter',
            name='meaning_short_str',
            field=models.CharField(default='', max_length=200),
        ),
    ]
